### ISSUE TITLE
[Bug] RMP Displays Incorrect Professor When No Ratings Exist

### ISSUE THREAD

**Issue by MStolen** [UTDNebula/utd-trends#189]
### What did you expect to happen?

When I search a professor who has on RMP, no data should display if the professor has no ratings.

### What happened?

A professor with a matching first name is displayed

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MStolen** [comment]
After looking further into it, the name is from the second professor in the linked search results the rating is from the first result.

**Comment by AbhiramTadepalli** [comment]
@MStolen do you mind sharing the professor's name (that you tried)?

**Comment by egsch** [comment]
I came across a professor where this happens: for Haoyi Song it shows data for Dongye Song. Maybe we need to check that the name matches when we're pulling RMP data (if the new scraper isn't already doing this).

**Comment by TyHil** [comment]
I believe this is resolved in with the new scraper. At least for Haoyi Song, the new scraper returns no data and I cannot find an entry on RMP for Haoyi Song, so that would be correct.

@MStolen can you confirm this is resolved on the new scraper? You can access it to test here: https://utd-trends-git-skedge-rmp-scraper-utdnebula.vercel.app

**Comment by TyHil** [comment]
Closing as resolved by #168
