### ISSUE TITLE
[Bug]: RHS grade distribution changes on professor profile when do next search for a course 

### ISSUE THREAD

**Issue by sparklingwter** [UTDNebula/utd-trends#256]
### What did you expect to happen?

The overall grade distribution on the professor's profile should not change- notice the total grade

### What happened?

Search: Alice Wang, CS 4341
Then search Alice Wang, CS 2340

Notice the grade distribution on the professor profile, it changes, but it should not.

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egsch** [comment]
Update: It happens when you change searches but not when you refresh the page. It (or something similar) is also happening with courses, where it's not showing all the course grades on the RHS when you search for some class+professor combos. I'm looking at how we save/reuse data to figure out how to stop it without unnecessary refetches.
